name: Simulate Realistic Site Traffic

on:
  schedule:
    - cron: "0 */4 * * *"  # כל 4 שעות
  workflow_dispatch:

jobs:
  simulate-traffic:
    runs-on: ubuntu-latest
    steps:
      - name: Checkout repository
        uses: actions/checkout@v2

      - name: Set up Python
        uses: actions/setup-python@v4
        with:
          python-version: '3.x'

      - name: Install dependencies
        run: |
          pip install selenium
          sudo apt-get update
          sudo apt-get install -y chromium-browser
          sudo ln -s /usr/bin/chromium-browser /usr/bin/google-chrome

      - name: Run Selenium Traffic Script
        run: python simulate_traffic.py
