name: Daily Traffic Bot

on:
  schedule:
    - cron: '0 10 * * *'
  workflow_dispatch:

jobs:
  run:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v3
      - name: Setup Python
        uses: actions/setup-python@v4
        with:
          python-version: '3.11'
      - name: Install dependencies
        run: |
          pip install selenium requests
      - name: Setup Chrome
        uses: browser-actions/setup-chrome@v1
      - name: Fetch sitemap links
        run: python fetch_sitemap.py
      - name: Simulate traffic
        run: python simulate_traffic.py
