
name: Traffic Bot Test

on:
  workflow_dispatch:

jobs:
  traffic:
    runs-on: ubuntu-latest

    steps:
    - name: Set up job
      uses: actions/checkout@v3

    - name: Setup Python
      uses: actions/setup-python@v4
      with:
        python-version: 3.11

    - name: Install dependencies
      run: |
        pip install selenium
        sudo apt-get update
        sudo apt-get install -y chromium-driver

    - name: Setup Chrome
      run: |
        sudo apt-get install -y chromium-browser

    - name: Run Simple Bot
      run: python simple_bot.py
